version: '3'

services:
  python-toolkit:
    image: foxonconsulting/langchain-toolkit:1.0.0
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./:/llama2-medical-chatbot
    container_name: "llama2-medical-chatbot-toolkit_cn"
    restart: unless-stopped
    command: bash -c "while true; do sleep 1; done"
